export const productsList = [
  {
    name: "nike air max pre-day",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/58903c0b-0afe-400e-8ac6-9bf3ccf940ba.webp",
    price: "1.979.000",
    brand: "nike",
    color: "black",
    description: "Lorem, ipsum dolor amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike sb force 58",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/3ca0e8ff-9564-46b0-a808-072cc0e8053a.webp",
    price: "1.099.000",
    brand: "nike",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike metcon 7",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/63a18e86-4df9-4615-b5f2-73c041358cd2.webp",
    price: "1.979.000",
    brand: "nike",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma suede classic xxi",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/suede_classic_xxi_red.webp",
    price: "980.000",
    brand: "puma",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma speedcat sparco",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/speedcat_sparco_red.webp",
    price: "1.400.000",
    brand: "puma",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma suede classic xxi",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/suede_classic_xxi_white.webp",
    price: "980.000",
    brand: "puma",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma super liga og retro",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/super_liga_og_retro.webp",
    price: "980.000",
    brand: "puma",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike jordan air 200e",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/d25948fc-4f2b-4791-90b1-25c5e51eaa4b.webp",
    price: "2.079.000",
    brand: "nike",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike air presto mid utility",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/646b995d-23a1-420f-9096-de99bd7e26bd.webp",
    price: "2.279.000",
    brand: "nike",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike air force 1 '07 lx",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/a3a96008-d81a-41c2-860c-f56709af8d4f.webp",
    price: "1.899.000",
    brand: "nike",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike air force 1 high '07 lv8",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/7a623120-f120-4346-8024-b7e9f62aab4c.webp",
    price: "1.919.000",
    brand: "nike",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike air jordan 1 retro high og",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/3249465b-a198-4399-8373-741d17da9935.webp",
    price: "2.569.000",
    brand: "nike",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike waffle trainer 2",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/59830ecf-e7f0-459d-bb4a-c8278cb5f751.webp",
    price: "1.279.000",
    brand: "nike",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike renew run 3",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/c4f90b49-4874-4404-b008-ed0992c18d62.webp",
    price: "1.299.000",
    brand: "nike",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma ca pro classic",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/ca_pro_classic.webp",
    price: "1.120.000",
    brand: "puma",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma suede classic xxi",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/suede_classic_xxi.webp",
    price: "980.000",
    brand: "puma",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma magnify nitro",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/magnify_nitro_blue.webp",
    price: "1.960.000",
    brand: "puma",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike sb shane premium",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/13afd4b8-79bf-41e9-a429-9b11087cd5ab.webp",
    price: "1.299.000",
    brand: "nike",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike air force 1 '07 craft",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/3e689630-e1ca-4e35-b08c-6f32e9afb14d.webp",
    price: "1.799.000",
    brand: "nike",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "nike sb ishod wair",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/e7111522-da86-4b40-888f-3d0df1be82b5.webp",
    price: "1.429.000",
    brand: "nike",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },

  {
    name: "puma suede classic xxi",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/suede_classic_xxi_blue.webp",
    price: "980.000",
    brand: "puma",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma electrify nitro green",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/electrify_nitro_green.webp",
    price: "1.400.000",
    brand: "puma",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "puma voyage nitro",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/voyage_nitro_green.webp",
    price: "1.820.000",
    brand: "puma",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans pride sentry",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/vans_pride_sentry_black.webp",
    price: "1.330.000",
    brand: "vans",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans 136 decon",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/vans_136_decon_blue.webp",
    price: "1.260.000",
    brand: "vans",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans color theory classic",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/vans_color_theory_classic.webp",
    price: "910.000",
    brand: "vans",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas nmd v3",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nmd_v3_white.webp",
    price: "2.240.000",
    brand: "adidas",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas daily 3.0 eco",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/daily_3.0_eco_white.webp",
    price: "910.000",
    brand: "adidas",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas galaxy 5",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/fy6736_sl_ecom.webp",
    price: "750.000",
    brand: "adidas",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas vl court 2.0",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/da9854_sl_ecom.webp",
    price: "900.000",
    brand: "adidas",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas harden vol 5",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/harden_vol_5_red.webp",
    price: "1.600.000",
    brand: "adidas",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas 4d fusio shoes",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/h04509_sl_ecom.webp",
    price: "3.500.000",
    brand: "adidas",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas donovan mtchell",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/donovan_mitchell_red.webp",
    price: "1.540.000",
    brand: "adidas",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas lite racer adapt 4.0",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/lite_racer_adapt_4.0_green.webp",
    price: "1.200.000",
    brand: "adidas",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas freak spark",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/freak_spark_red.webp",
    price: "1.050.000",
    brand: "adidas",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas supernova",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/supernova_green.webp",
    price: "1.160.000",
    brand: "adidas",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas icon 7 tpu",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/icon_7_tpu_red.webp",
    price: "952.000",
    brand: "adidas",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas barricade",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/gz8482_sl_ecom.webp",
    price: "2.200.000",
    brand: "adidas",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas supernova",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/supernova_red.webp",
    price: "1.160.000",
    brand: "adidas",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas 4dfwd x parley",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/fw3012_sl_ecom.webp",
    price: "1.900.000",
    brand: "adidas",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas 4dfwd x parley",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/gx6313_sl_ecom.webp",
    price: "4.000.000",
    brand: "adidas",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas t-mac 2.0 restomod svsm",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/t-mac_2.0_restomod_svsm_green.webp",
    price: "1.820.000",
    brand: "adidas",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas ultraboost 5.0 dna",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/ultraboost_5.0_dna_green.webp",
    price: "3.300.000",
    brand: "adidas",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse unt1tl3d translucent barcode",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A02599C_A_08X1.jpg",
    price: "1.050.000",
    brand: "converse",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck 70 archive paint splatter",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A01171C_A_08X1.jpg",
    price: "1.190.000",
    brand: "converse",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse x peanuts chuck taylor all star",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A02573C_A_08X1.jpg",
    price: "980.000",
    brand: "converse",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck taylor all star cx pull tab",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A02037C_E_08X1.jpg",
    price: "1.050.000",
    brand: "converse",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck taylor all star translucent barcode",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A02583C_A_08X1.jpg",
    price: "910.000",
    brand: "converse",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck taylor all star leather",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/135251C_A_08X1.jpg",
    price: "980.000",
    brand: "converse",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck 70 crafted stripe",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A00472C_D_08X1.jpg",
    price: "1.190.000",
    brand: "converse",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck taylor all star cx seasonal color",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A03295C_A_08X1.jpg",
    price: "1.050.000",
    brand: "converse",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck 70 it's possible",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A01736C_A_08X1.jpg",
    price: "1.330.000",
    brand: "converse",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans era 59",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/vans_era_59_red.webp",
    price: "840.000",
    brand: "vans",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas zx 5k boost",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/zx_5k_boost_green.webp",
    price: "2.240.000",
    brand: "adidas",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas lite racer adapt 4.0 shoes",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/h04296_sl_ecom.webp",
    price: "1.200.000",
    brand: "adidas",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas lite racer 3.0 shoes",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/gw7954_sl_ecom.webp",
    price: "750.000",
    brand: "adidas",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas 4d fwd",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/gx2977_sl_ecom.jpg",
    price: "3.500.000",
    brand: "adidas",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance 574 court",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/ct574brg_nb_02_i.webp",
    price: "1.260.000",
    brand: "new_balance",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance x aries fresh foam 1080v11",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/m1080z11_nb_02_i.webp",
    price: "2.520.000",
    brand: "new_balance",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric jamie foy 306 lanceless",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm306lbw_nb_02_i.webp",
    price: "1.120.000",
    brand: "new_balance",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans rowan",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/vans_rowan_blue.webp",
    price: "980.000",
    brand: "vans",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans sk8 hi",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/sk8_hi_green.webp",
    price: "1.120.000",
    brand: "vans",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck taylor all star washed canvas",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A02584C_D_08X1.jpg",
    price: "910.000",
    brand: "converse",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck taylor all star patchwork",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A02030C_A_08X1.jpg",
    price: "910.000",
    brand: "converse",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse unt1tl3d translucent barcode",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/A02598C_A_08X1.jpg",
    price: "1.050.000",
    brand: "converse",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "converse chuck taylor all star classic",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/M7650_A_08X1.jpg",
    price: "910.000",
    brand: "converse",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas ultraboost 5.0 dna shoes",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/gx9332_sl_ecom.webp",
    price: "3.300.000",
    brand: "adidas",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas nmd r1",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nmd_r1_white.webp",
    price: "2.100.000",
    brand: "adidas",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas stan smith",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/stan_smith_white.webp",
    price: "1.300.000",
    brand: "adidas",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "adidas ultraboost 4.0 dna shoes",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/ultraboost_4.0_dna_white.webp",
    price: "2.660.000",
    brand: "adidas",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance fuelcell shift tr",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/mxshftlk_nb_02_i.webp",
    price: "1.400.000",
    brand: "new_balance",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric tiago lemos 1010",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm1010bb_nb_02_i.webp",
    price: "1.540.000",
    brand: "new_balance",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric 212 pro court",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm212bss_nb_02_i.webp",
    price: "980.000",
    brand: "new_balance",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance 210 pro court",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/ct210trb_nb_02_i.webp",
    price: "910.000",
    brand: "new_balance",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric tiago lemos 1010",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm1010gm_nb_02_i.webp",
    price: "1.540.000",
    brand: "new_balance",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok lavante trail 2",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_lavante_trail_2_green.webp",
    price: "1.190.000",
    brand: "reebok",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok looney tunes",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/rebook_looney_tunes.jpg",
    price: "1.680.000",
    brand: "reebok",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok zig kinetica ii",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_zig_kinetica_ii.jpg",
    price: "2.380.000",
    brand: "reebok",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans old skool",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/vans_old_skool_red.webp",
    price: "910.000",
    brand: "vans",
    color: "red",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans pride old skool",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/pride_old_skool_white.webp",
    price: "1.050.000",
    brand: "vans",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric jamie foy 306",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm306slc_nb_02_i.webp",
    price: "1.260.000",
    brand: "new_balance",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric jamie foy 306",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm306ugc_nb_02_i.webp",
    price: "1.260.000",
    brand: "new_balance",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric 288 sport",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm288sdb_nb_02_i.webp",
    price: "1.330.000",
    brand: "new_balance",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance fuelcell 996v4",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/mch996l4_nb_02_i.webp",
    price: "2.030.000",
    brand: "new_balance",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "new balance numeric 288 sport",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/nm288sgh_nb_02_i.webp",
    price: "1.260.000",
    brand: "new_balance",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok nano x2",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_nano_x2_black.webp",
    price: "1.890.000",
    brand: "reebok",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok trail cruiser",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_trail_cruiser_black.webp",
    price: "1.260.000",
    brand: "reebok",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok victory g",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_victory_g_blue.webp",
    price: "1.680.000",
    brand: "reebok",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok zig dynamica 2",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_zig_dynamica_2_blue.webp",
    price: "1.120.000",
    brand: "reebok",
    color: "blue",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok answer iv",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_answer_iv_green.webp",
    price: "2.100.000",
    brand: "reebok",
    color: "green",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok tyrrell winston",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/tyrrell_winston.webp",
    price: "2.240.000",
    brand: "reebok",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "reebok nano x2",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/reebok_nano_x2.webp",
    price: "1.890.000",
    brand: "reebok",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans colfax boot",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/vans_colfax_boot_black.jpg",
    price: "1.470.000",
    brand: "vans",
    color: "black",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
  {
    name: "vans skate authentic",
    img: "https://res.cloudinary.com/ricky-assets/image/upload/shoeshop/skate_authentic.webp",
    price: "910.000",
    brand: "vans",
    color: "white",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum eos tempore tenetur exercitationem maiores reiciendis totam pariatur. Illo, ea doloremque!",
  },
];
